export enum FacebookSourceKeys {
  'Facebook',
  'facebook',
  'fb',
  'Fb',
  'Ig',
  'ig',
  'Fb_ig',
  'Fb/ig',
  'Instagram',
  'instagram',
  'www.facebook.com',
  'm.facebook.com',
  'l.facebook.com',
  'lm.facebook.com',
  'instagram.com',
  'www.instagram.com',
}
