interface StatusCodes {
  [key: number]: { message: string; type: 'error' | 'success' };
}

export const statusCodes: StatusCodes = {
  0: { message: 'Business not active.', type: 'error' },
  1: { message: 'Business not found.', type: 'error' },
  2: { message: 'User not found.', type: 'error' },
  3: { message: 'No business found.', type: 'error' },
  4: { message: 'Business limit already reached.', type: 'error' },
  5: { message: 'Business name already exists.', type: 'error' },
  6: { message: 'Business already deactivated.', type: 'error' },
  7: { message: 'Business deactivated.', type: 'success' },
  8: {
    message: 'Business name or domain name does not exist.',
    type: 'success',
  },
  9: { message: 'Domain name successfully verified.', type: 'success' },
  10: { message: 'Invalid date format.', type: 'error' },
  11: { message: 'No ad sets found.', type: 'error' },
  12: { message: 'No ads found.', type: 'error' },
  13: { message: 'No campaign found.', type: 'error' },
  14: { message: 'No ad set found.', type: 'error' },
  15: { message: 'No ad found.', type: 'error' },
  16: { message: 'No campaigns found.', type: 'error' },
  17: { message: 'No visitors found.', type: 'error' },
  18: { message: 'No sources found.', type: 'error' },
  19: { message: 'Profile Updated.', type: 'success' },
  20: { message: 'Profile cannot be updated.', type: 'error' },
  21: {
    message: 'The new password cannot be the same as your old password.',
    type: 'error',
  },
  22: { message: 'Password changed.', type: 'success' },
  23: {
    message: 'The current password you entered does not match our records.',
    type: 'error',
  },
  24: { message: 'User logged out successfully.', type: 'success' },
  25: { message: 'Increase request submitted.', type: 'success' },
  26: { message: 'Increase request already submitted.', type: 'error' },
  27: { message: 'No increase requests.', type: 'error' },
  28: { message: 'No roles found.', type: 'error' },
  29: { message: 'Invalid user role.', type: 'error' },
  30: { message: 'Usage cannot be found.', type: 'error' },
  31: {
    message: 'Active subscription cannot be found for this user.',
    type: 'error',
  },
  32: { message: 'No staff found.', type: 'error' },
  33: { message: 'No access found.', type: 'error' },
  34: { message: 'Access removed.', type: 'success' },
  35: { message: 'Access set.', type: 'success' },
  36: { message: 'Staff removed.', type: 'success' },
  37: { message: 'Staff successfully registered.', type: 'success' },
  38: {
    message: 'A user with the details you entered already exists.',
    type: 'error',
  },
  39: { message: 'Manager successfully registered.', type: 'success' },
  40: { message: 'Beta code entered does not exist.', type: 'error' },
  41: { message: 'User already exists.', type: 'error' },
  42: {
    message:
      'Account is not activated. Check your email for an activation link.',
    type: 'error',
  },
  43: { message: 'Link valid.', type: 'success' },
  44: { message: 'Link invalid.', type: 'error' },
  45: {
    message: 'Password cannot be the same as your old password.',
    type: 'error',
  },
  46: {
    message: 'Password successfully reset. You may now login.',
    type: 'success',
  },
  47: { message: 'Account verified. You may now login.', type: 'success' },
  48: {
    message: 'Notification settings updated successfully.',
    type: 'success',
  },
  49: { message: 'Notification settings cannot be updated.', type: 'error' },
  50: { message: 'Email sent.', type: 'success' },
  51: { message: 'Beta code created. Sent user an email.', type: 'success' },
  52: { message: 'Email already exists with a beta code.', type: 'error' },
  53: { message: 'Business profile updated.', type: 'success' },
  54: {
    message:
      'Could not update the business profile at this time. Please try again later.',
    type: 'error',
  },
  55: { message: 'Visitor not found.', type: 'error' },
  56: { message: 'Invalid email or password.', type: 'error' },
  57: { message: 'Facebook user access set.', type: 'success' },
  58: { message: 'Facebook user access removed.', type: 'success' },
  59: { message: 'Facebook access expired or does not exist.', type: 'error' },
  60: {
    message: 'Could not load ad accounts at this time. Please try again later.',
    type: 'error',
  },
  61: { message: 'Facebook ad account set.', type: 'success' },
  62: { message: 'Facebook ad account removed.', type: 'success' },
  63: { message: 'Performance: Invalid campaign source.', type: 'error' },
  64: {
    message: 'Performance: Missing a Facebook campaign ID.',
    type: 'error',
  },
  65: {
    message: 'Performance: Successfully matched campaign.',
    type: 'success',
  },
  66: {
    message:
      'Performance: An error occured while matching. Please try again later.',
    type: 'error',
  },
  67: {
    message: 'Performance: Facebook access does not exist or has expired.',
    type: 'error',
  },
  68: { message: 'Performance: Facebook returned no results.', type: 'error' },
  69: {
    message:
      'Campaign Info: Error loading campaign insights. Please try again later',
    type: 'error',
  },
  70: {
    message: 'Campaign Info: Valid start date and end date required.',
    type: 'error',
  },
  71: { message: 'A valid Facebook campaign IDs are required.', type: 'error' },
  72: { message: 'No permission.', type: 'error' },
  73: { message: 'Bolt: Closed Mode turned on.', type: 'success' },
  74: { message: 'Bolt: Closed Mode turned off.', type: 'success' },
  75: { message: 'Platform settings not found.', type: 'error' },
  76: { message: 'Need manager access.', type: 'error' },
  77: { message: 'Staff limit already reached.', type: 'error' },
  78: { message: 'Business external platform updated.', type: 'success' },
  79: { message: 'User already exist.', type: 'error' },
  80: { message: 'Valid request required.', type: 'error' },
  81: { message: 'Unauthorized to connect.', type: 'error' },
  82: { message: 'No visits found.', type: 'error' },
  83: { message: 'No page views found.', type: 'error' },
  84: { message: 'Visit not found.', type: 'error' },
  85: { message: 'Purchase not found.', type: 'error' },
  86: { message: 'Nothing to revoke.', type: 'error' },
  87: { message: 'Invalid permissions.', type: 'error' },
  88: { message: 'No active subscription.', type: 'error' },
  89: { message: 'Wrong plan & product combination.', type: 'error' },
  90: { message: 'Subscription updated.', type: 'success' },
  91: { message: 'Invalid quantity.', type: 'error' },
  92: { message: 'Invalid subscription product.', type: 'error' },
  93: { message: 'Cannot find subscription product.', type: 'error' },
  94: { message: 'Invalid quantity update type.', type: 'error' },
  95: { message: 'Not available during a free trial.', type: 'error' },
  96: { message: 'Card Changed.', type: 'success' },
  97: { message: 'Invalid plan code.', type: 'error' },
  99: { message: 'Already subscribed.', type: 'error' },
  100: { message: 'No valid plan.', type: 'error' },
  101: { message: 'Upgrade incomplete. Payment failed.', type: 'error' },
  102: {
    message: 'Upgrade incomplete. A product could not be found.',
    type: 'error',
  },
  104: { message: 'Nothing to remove.', type: 'error' },
  105: { message: 'Trial ended.', type: 'success' },
  106: { message: 'Already on an active plan.', type: 'error' },
  107: { message: 'Subscription canceled.', type: 'success' },
  108: { message: 'Cannot find invoice.', type: 'error' },
  109: { message: 'Invoice already paid.', type: 'error' },
  110: { message: 'Invoice successfully paid.', type: 'success' },
  111: { message: 'No user found.', type: 'error' },
  112: {
    message: 'A business with this name already exists.',
    type: 'error',
  },
  113: {
    message: 'Sirge is unavailable in the country you selected.',
    type: 'error',
  },
  114: { message: 'Account frozen.', type: 'error' },
  115: { message: 'Subscribed to plan.', type: 'success' },
  116: { message: 'Plan could not be found.', type: 'error' },
  117: { message: 'Plan products could not be found.', type: 'error' },
  118: { message: 'Business activated.', type: 'success' },
  119: { message: 'Business not found or already active.', type: 'error' },
  120: {
    message: 'Selected campaigns must be seperated by a comma.',
    type: 'error',
  },
  121: {
    message: 'Selected ad sets must be seperated by a comma.',
    type: 'error',
  },
  122: { message: 'Timezone and Currency cannot be changed.', type: 'error' },
  123: { message: 'Timezone and Currency selected.', type: 'success' },
  124: { message: 'An error occured. Please try again later.', type: 'error' },
  125: { message: 'No campaign ID found.', type: 'error' },
  126: { message: 'No ad set ID found.', type: 'error' },
  127: { message: 'No ad ID found.', type: 'error' },
  128: {
    message: 'Selected ad sets must be seperated by a comma.',
    type: 'error',
  },
  129: { message: 'The page number you selected is invalid.', type: 'error' },
  130: { message: 'Invalid sort order.', type: 'error' },
  131: { message: 'Invalid sort field.', type: 'error' },
  132: { message: 'Invalid date range.', type: 'error' },
  133: { message: 'Invalid product option.', type: 'error' },
  134: { message: 'Invalid entry.', type: 'error' },
  135: { message: 'Email sent.', type: 'success' },
  136: { message: 'User not found.', type: 'error' },
  137: { message: 'Not required.', type: 'error' },
  138: { message: 'Could not verify your code.', type: 'error' },
  139: { message: 'Code verified.', type: 'success' },
  140: {
    message: 'Two-factor settings updated successfully.',
    type: 'success',
  },
  141: { message: 'Two-factor settings cannot be updated.', type: 'error' },
  142: { message: 'Two-factor code could not be sent.', type: 'error' },
  143: { message: 'Two-factor authentication code sent.', type: 'success' },
  144: { message: 'Two-factor not enabled.', type: 'error' },
  145: { message: 'Two-factor code required.', type: 'error' },
  146: { message: 'Two-factor removed.', type: 'success' },
  147: { message: 'Two-factor already enabled.', type: 'error' },
  148: { message: 'Two-factor enabled.', type: 'success' },
  149: { message: 'Facebook connection settings updated.', type: 'success' },
  150: { message: 'No results.', type: 'error' },
  151: { message: 'Selected ids in invalid format.', type: 'error' },
  152: {
    message: 'You are already registered for the affiliate program.',
    type: 'error',
  },
  153: {
    message: 'You are not registered for the affiliate program.',
    type: 'error',
  },
  154: { message: 'PayPal email successfully changed.', type: 'success' },
  155: { message: 'Could not change PayPal email.', type: 'error' },
  156: {
    message: 'User has either an active or canceled subscription.',
    type: 'error',
  },
  157: { message: 'Premium usage charge created.', type: 'error' },
  158: { message: 'Not available on current plan.', type: 'error' },
  159: { message: 'Auto scaling setting changed.', type: 'success' },
  160: { message: 'Auto scaling is not on.', type: 'error' },
  161: { message: 'Retention period updated.', type: 'success' },
  162: { message: 'Expired page views deleted.', type: 'success' },
  163: { message: 'Unsupported country selected.', type: 'error' },
  164: { message: 'No client billing account found.', type: 'error' },
  165: { message: 'Client billing account deleted.', type: 'success' },
  166: { message: 'Client billing account created.', type: 'success' },
  167: {
    message: 'Invalid bank information. Please verify your entry.',
    type: 'error',
  },
  168: { message: 'Bank information set.', type: 'success' },
  169: {
    message: 'Instant payouts is not available in your country.',
    type: 'error',
  },
  170: { message: 'Insufficient funds.', type: 'error' },
  171: {
    message: 'Your withdrawal request has been submitted.',
    type: 'success',
  },
  172: { message: 'Client Billing: Product created.', type: 'success' },
  173: { message: 'Client Billing: Subscription created.', type: 'success' },
  174: { message: 'Failed to get bolt plus product id.', type: 'error' },
  175: { message: 'The code you entered is invalid.', type: 'error' },
  176: { message: 'The code you entered has been applied.', type: 'success' },
  178: { message: 'Event log recorded.', type: 'success' },
  179: { message: 'Staff deleted', type: 'success' },
  180: { message: 'Coaching call credit used', type: 'success' },
  181: { message: 'No coaching call credit available', type: 'error' },
  182: { message: 'Unauthorized', type: 'error' },
  183: { message: 'Plan code already in use', type: 'error' },
  184: { message: 'Unknown Error', type: 'error' },
  185: { message: 'No authenticated user', type: 'error' },
  186: { message: 'Invalid tik tok access', type: 'error' },
  187: { message: 'Tik tok account id not found', type: 'error' },
  188: { message: 'Tik tok account name not found', type: 'error' },
  189: { message: 'No Credit Transaction Found.', type: 'error' },
  190: { message: 'No ad account selected.', type: 'error' },
  191: { message: 'Invalid source', type: 'error' },
  192: { message: 'Ad sets not found', type: 'error' },
  193: { message: 'Exchange rate not found', type: 'error' },
  194: { message: 'Tik tok ad not found', type: 'error' },
  195: { message: 'Tik tok ad account set', type: 'error' },
  196: { message: 'Visitors not found', type: 'error' },
  197: { message: 'You need send at least one roas goals', type: 'error' },
};

/**
 * Throws an error with a given status code
 *
 * Usage: throw new StatusCodeError(1);
 */
export class StatusCodeError extends Error {
  code: number;

  constructor(statusCode: number) {
    const { message } = statusCodes[statusCode];

    super(message);

    this.code = statusCode;
  }
}
